import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Organization } from '../../organizations/entities/create-organization.entityes';
import { TenantManager } from '../tenant-manager.service';
import { Permission } from '../../permission/entities/permission.entity';

@Injectable()
export class PermissionsSeeder {
  constructor(
    @InjectRepository(Organization)
    private orgRepo: Repository<Organization>,
    private tenantManager: TenantManager,
  ) {}

  private permissionsData = [
    { id: 1, name: 'admin-menu', permissionGroup: 'Admin', guardName: 'web' },
    { id: 2, name: 'content-menu', permissionGroup: 'Content', guardName: 'web' },
    { id: 3, name: 'create-folder', permissionGroup: 'Content', guardName: 'web' },
    { id: 4, name: 'import-video', permissionGroup: 'Content', guardName: 'web' },
    { id: 5, name: 'import-pdf', permissionGroup: 'Content', guardName: 'web' },
    { id: 6, name: 'import-test', permissionGroup: 'Content', guardName: 'web' },
    { id: 7, name: 'users-menu', permissionGroup: 'User', guardName: 'web' },
    { id: 8, name: 'users-list', permissionGroup: 'User', guardName: 'web' },
    { id: 9, name: 'login-analytics', permissionGroup: 'User', guardName: 'web' },
    { id: 10, name: 'send-notification', permissionGroup: 'User', guardName: 'web' },
    { id: 11, name: 'course-notifications', permissionGroup: 'User', guardName: 'web' },
    { id: 18, name: 'banner-menu', permissionGroup: 'Banner', guardName: 'web' },
    { id: 19, name: 'banner-list', permissionGroup: 'Banner', guardName: 'web' },
    { id: 20, name: 'add-banner', permissionGroup: 'Banner', guardName: 'web' },
    { id: 21, name: 'delete-banner', permissionGroup: 'Banner', guardName: 'web' },
    { id: 22, name: 'publish-unpublish-banner', permissionGroup: 'Banner', guardName: 'web' },
    { id: 23, name: 'stream-menu', permissionGroup: 'Stream', guardName: 'web' },
    { id: 24, name: 'add-stream', permissionGroup: 'Stream', guardName: 'web' },
    { id: 25, name: 'view-stream', permissionGroup: 'Stream', guardName: 'web' },
    { id: 26, name: 'edit-stream', permissionGroup: 'Stream', guardName: 'web' },
    { id: 27, name: 'delete-stream', permissionGroup: 'Stream', guardName: 'web' },
    { id: 34, name: 'course-menu', permissionGroup: 'Course', guardName: 'web' },
    { id: 35, name: 'add-course', permissionGroup: 'Course', guardName: 'web' },
    { id: 36, name: 'view-course', permissionGroup: 'Course', guardName: 'web' },
    { id: 37, name: 'edit-course', permissionGroup: 'Course', guardName: 'web' },
    { id: 38, name: 'publish-unpublish-course', permissionGroup: 'Course', guardName: 'web' },
    { id: 39, name: 'delete-course', permissionGroup: 'Course', guardName: 'web' },
    { id: 40, name: 'live-event-menu', permissionGroup: 'Live Event', guardName: 'web' },
    { id: 41, name: 'live-chat', permissionGroup: 'Live Event', guardName: 'web' },
    { id: 42, name: 'assign-course-menu', permissionGroup: 'Assign Course', guardName: 'web' },
    { id: 43, name: 'assign-course', permissionGroup: 'Assign Course', guardName: 'web' },
    { id: 44, name: 'view-assign-course', permissionGroup: 'Assign Course', guardName: 'web' },
    { id: 45, name: 'delete-assign-course', permissionGroup: 'Assign Course', guardName: 'web' },
    { id: 46, name: 'view-enrolled-course', permissionGroup: 'Assign Course', guardName: 'web' },
    { id: 47, name: 'delete-enrolled-course', permissionGroup: 'Assign Course', guardName: 'web' },
    { id: 48, name: 'online-payment', permissionGroup: 'Assign Course', guardName: 'web' },
    { id: 49, name: 'promotion-menu', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 50, name: 'add-promotion', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 51, name: 'edit-promotion', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 52, name: 'view-promotion', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 53, name: 'promotion-detail', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 54, name: 'publish-unpublish-promotion', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 55, name: 'delete-promotion', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 56, name: 'teacher-menu', permissionGroup: 'Teacher', guardName: 'web' },
    { id: 57, name: 'add-teacher', permissionGroup: 'Teacher', guardName: 'web' },
    { id: 58, name: 'edit-teacher', permissionGroup: 'Teacher', guardName: 'web' },
    { id: 59, name: 'view-teacher', permissionGroup: 'Teacher', guardName: 'web' },
    { id: 60, name: 'delete-teacher', permissionGroup: 'Teacher', guardName: 'web' },
    { id: 67, name: 'general-settings', permissionGroup: 'Setting', guardName: 'web' },
    { id: 68, name: 'default-routing-account', permissionGroup: 'Setting', guardName: 'web' },
    { id: 69, name: 'delete-default-routing-account', permissionGroup: 'Setting', guardName: 'web' },
    { id: 70, name: 'add-coin', permissionGroup: 'Setting', guardName: 'web' },
    { id: 71, name: 'create-role', permissionGroup: 'Admin', guardName: 'web' },
    { id: 72, name: 'edit-role', permissionGroup: 'Admin', guardName: 'web' },
    { id: 73, name: 'delete-role', permissionGroup: 'Admin', guardName: 'web' },
    { id: 74, name: 'create-admin', permissionGroup: 'Admin', guardName: 'web' },
    { id: 75, name: 'edit-admin', permissionGroup: 'Admin', guardName: 'web' },
    { id: 76, name: 'delete-admin', permissionGroup: 'Admin', guardName: 'web' },
    { id: 77, name: 'other-menu', permissionGroup: 'Other', guardName: 'web' },
    { id: 78, name: 'add-live-event', permissionGroup: 'Live Event', guardName: 'web' },
    { id: 79, name: 'edit-live-event', permissionGroup: 'Live Event', guardName: 'web' },
    { id: 80, name: 'import-bulk-test', permissionGroup: 'Other', guardName: 'web' },
    { id: 81, name: 'test-menu', permissionGroup: 'Test', guardName: 'web' },
    { id: 82, name: 'add-test', permissionGroup: 'Test', guardName: 'web' },
    { id: 83, name: 'edit-test', permissionGroup: 'Test', guardName: 'web' },
    { id: 84, name: 'view-question', permissionGroup: 'Test', guardName: 'web' },
    { id: 85, name: 'test-rank', permissionGroup: 'Test', guardName: 'web' },
    { id: 86, name: 'delete-test', permissionGroup: 'Test', guardName: 'web' },
    { id: 87, name: 'delete-all-question', permissionGroup: 'Question', guardName: 'web' },
    { id: 88, name: 'download-csv', permissionGroup: 'Question', guardName: 'web' },
    { id: 89, name: 'edit-question', permissionGroup: 'Question', guardName: 'web' },
    { id: 90, name: 'delete-question', permissionGroup: 'Question', guardName: 'web' },
    { id: 91, name: 'details', permissionGroup: 'Question', guardName: 'web' },
    { id: 92, name: 'view-live-event', permissionGroup: 'Live Event', guardName: 'web' },
    { id: 93, name: 'delete-live-event', permissionGroup: 'Live Event', guardName: 'web' },
    { id: 94, name: 'publish-unpublish-event', permissionGroup: 'Live Event', guardName: 'web' },
    { id: 95, name: 'add-video', permissionGroup: 'Video', guardName: 'web' },
    { id: 96, name: 'edit-video', permissionGroup: 'Video', guardName: 'web' },
    { id: 97, name: 'view-video', permissionGroup: 'Video', guardName: 'web' },
    { id: 98, name: 'delete-video', permissionGroup: 'Video', guardName: 'web' },
    { id: 99, name: 'publish-unpublish-video', permissionGroup: 'Video', guardName: 'web' },
    { id: 100, name: 'add-pdf', permissionGroup: 'PDF', guardName: 'web' },
    { id: 101, name: 'edit-pdf', permissionGroup: 'PDF', guardName: 'web' },
    { id: 102, name: 'view-pdf', permissionGroup: 'PDF', guardName: 'web' },
    { id: 103, name: 'delete-pdf', permissionGroup: 'PDF', guardName: 'web' },
    { id: 104, name: 'publish-unpublish-pdf', permissionGroup: 'PDF', guardName: 'web' },
    { id: 105, name: 'edit-category', permissionGroup: 'Category', guardName: 'web' },
    { id: 106, name: 'delete-category', permissionGroup: 'Category', guardName: 'web' },
    { id: 107, name: 'add-question', permissionGroup: 'Question', guardName: 'web' },
    { id: 108, name: 'ticket', permissionGroup: 'Other', guardName: 'web' },
    { id: 109, name: 'ticket-status', permissionGroup: 'Other', guardName: 'web' },
    { id: 110, name: 'view-ticket', permissionGroup: 'Other', guardName: 'web' },
    { id: 111, name: 'OMR-Sheet-menu', permissionGroup: 'OMR', guardName: 'web' },
    { id: 112, name: 'add-OMR', permissionGroup: 'OMR', guardName: 'web' },
    { id: 113, name: 'view-OMR', permissionGroup: 'OMR', guardName: 'web' },
    { id: 114, name: 'edit-OMR', permissionGroup: 'OMR', guardName: 'web' },
    { id: 115, name: 'delete-OMR', permissionGroup: 'OMR', guardName: 'web' },
    { id: 116, name: 'social-media', permissionGroup: 'Setting', guardName: 'web' },
    { id: 117, name: 'add-social-media', permissionGroup: 'Setting', guardName: 'web' },
    { id: 118, name: 'edit-social-media', permissionGroup: 'Setting', guardName: 'web' },
    { id: 119, name: 'view-social-media', permissionGroup: 'Setting', guardName: 'web' },
    { id: 120, name: 'delete-social-media', permissionGroup: 'Setting', guardName: 'web' },
    { id: 121, name: 'news-banner', permissionGroup: 'Banner', guardName: 'web' },
    { id: 122, name: 'add-quiz', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 123, name: 'view-quiz', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 124, name: 'edit-quiz', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 125, name: 'add-quiz-category', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 126, name: 'add-quiz-ques', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 127, name: 'view-quiz-ques', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 128, name: 'delete-quiz', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 129, name: 'delete-all-quiz-ques', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 130, name: 'download-quiz-csv', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 131, name: 'edit-quiz-ques', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 132, name: 'details-quiz', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 133, name: 'delete-quiz-ques', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 134, name: 'quiz-menu', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 135, name: 'in-app-notifications', permissionGroup: 'User', guardName: 'web' },
    { id: 139, name: 'notification-history', permissionGroup: 'User', guardName: 'web' },
    { id: 140, name: 'super-stream-menu', permissionGroup: 'Super Stream', guardName: 'web' },
    { id: 141, name: 'add-super-stream', permissionGroup: 'Super Stream', guardName: 'web' },
    { id: 142, name: 'view-super-stream', permissionGroup: 'Super Stream', guardName: 'web' },
    { id: 143, name: 'edit-super-stream', permissionGroup: 'Super Stream', guardName: 'web' },
    { id: 144, name: 'delete-super-stream', permissionGroup: 'Super Stream', guardName: 'web' },
    { id: 145, name: 'top-teacher-menu', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 146, name: 'add-top-teacher', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 147, name: 'view-top-teacher', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 148, name: 'edit-top-teacher', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 149, name: 'delete-top-teacher', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 150, name: 'top-student-menu', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 151, name: 'add-top-student', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 152, name: 'view-top-student', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 153, name: 'edit-top-student', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 154, name: 'delete-top-student', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 155, name: 'frame-menu', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 156, name: 'add-frame', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 157, name: 'view-frame', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 158, name: 'edit-frame', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 159, name: 'delete-frame', permissionGroup: 'Promotion', guardName: 'web' },
    { id: 160, name: 'payment-menu', permissionGroup: 'Payment', guardName: 'web' },
    { id: 161, name: 'view-payment-leads', permissionGroup: 'Assign Course', guardName: 'web' },
    { id: 162, name: 'view-success-payments', permissionGroup: 'Assign Course', guardName: 'web' },
    { id: 163, name: 'export-payment-data', permissionGroup: 'Payment', guardName: 'web' },
    { id: 164, name: 'export-csv', permissionGroup: 'Export', guardName: 'web' },
    { id: 165, name: 'export-payment-csv', permissionGroup: 'Export', guardName: 'web' },
    { id: 166, name: 'export-leads-csv', permissionGroup: 'Export', guardName: 'web' },
    { id: 171, name: 'add-in-app-notification', permissionGroup: 'User', guardName: 'web' },
    { id: 172, name: 'edit-in-app-notification', permissionGroup: 'User', guardName: 'web' },
    { id: 173, name: 'delete-in-app-notification', permissionGroup: 'User', guardName: 'web' },
    { id: 174, name: 'view-in-app-notification', permissionGroup: 'User', guardName: 'web' },
    { id: 175, name: 'add-category', permissionGroup: 'Content', guardName: 'web' },
    { id: 176, name: 'view-banner', permissionGroup: 'Banner', guardName: 'web' },
    { id: 177, name: 'publish-unpublish-live-event', permissionGroup: 'Live Event', guardName: 'web' },
    { id: 178, name: 'delete-assigned-course', permissionGroup: 'Assign Course', guardName: 'web' },
    { id: 179, name: 'setting-menu', permissionGroup: 'Setting', guardName: 'web' },
    { id: 180, name: 'wallet-menu', permissionGroup: 'Wallet', guardName: 'web' },
    { id: 181, name: 'view-coin', permissionGroup: 'Wallet', guardName: 'web' },
    { id: 182, name: 'ticket-menu', permissionGroup: 'Ticket', guardName: 'web' },
    { id: 183, name: 'edit-ticket', permissionGroup: 'Ticket', guardName: 'web' },
    { id: 184, name: 'publish-unpublish-OMR', permissionGroup: 'OMR', guardName: 'web' },
    { id: 185, name: 'add-quiz-question', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 186, name: 'edit-quiz-question', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 187, name: 'delete-quiz-question', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 188, name: 'view-quiz-question', permissionGroup: 'Quiz', guardName: 'web' },
    { id: 189, name: 'import-bulk', permissionGroup: 'Other', guardName: 'web' },
    { id: 190, name: 'course-doubt', permissionGroup: 'Other', guardName: 'web' },
    { id: 191, name: 'edit-user', permissionGroup: 'User', guardName: 'web' },
    { id: 192, name: 'block-course', permissionGroup: 'Assign Course', guardName: 'web' },
    { id: 193, name: 'user-list-csv', permissionGroup: 'Export', guardName: 'web' },
    { id: 194, name: 'blog-menu', permissionGroup: 'Blog Management', guardName: 'web' },
    { id: 195, name: 'dashboard-analytics-view', permissionGroup: 'Dashboard', guardName: 'web' },
    { id: 196, name: 'assign-analytics-view', permissionGroup: 'Assignment', guardName: 'web' },
    { id: 197, name: 'payment-analytics-view', permissionGroup: 'Payment', guardName: 'web' },
  ];

  async seedForOrganization(subdomain: string) {
    const tenantDataSource = await this.tenantManager.getTenantConnection(subdomain);
    const permissionRepo = tenantDataSource.getRepository(Permission);

    for (const perm of this.permissionsData) {
      const existing = await permissionRepo.findOne({ where: { id: perm.id } });
      if (!existing) {
        const permission = permissionRepo.create({
          id: perm.id,
          name: perm.name,
          permissionGroup: perm.permissionGroup,
          guardName: perm.guardName,
          status: true,
        });
        await permissionRepo.save(permission);
        console.log(`✅ Created permission: ${perm.name}`);
      } else {
        console.log(`⚠️ Permission already exists: ${perm.name}`);
      }
    }

    return {
      message: 'Permissions seeded successfully',
      count: this.permissionsData.length,
    };
  }
}
